version: '3.7'

services:
  local-db:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - default  
    ports:
      - "30001:3306"
    volumes:
      - localdbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: cloudcall123
      MYSQL_DATABASE: localdefaultdb

  local-db-migrations:
    depends_on:
      - local-db
    networks:
      - default     
    image: flyway/flyway
    volumes:
      - ./db/flyway/sql:/flyway/sql
      - ./db/flyway/config:/flyway/conf
    command: migrate
    environment:
      FLYWAY_EDITION: community
      FLYWAY_CONFIG_FILES: /flyway/conf/cloudcall.conf
      FLYWAY_LOCATIONS: filesystem:/flyway/sql

volumes:
  localdbdata: